#!/usr/bin/env node
/**
 * Generate the human-readable taxonomy documents.
 *
 * The YAML files are the right format to author in. They are a poor format to
 * AUDIT in: you cannot read 43 files linearly, and the rendered viewer is a
 * JavaScript page that cannot be diffed, printed, or pulled into a
 * spreadsheet. An auditor needs all three of those things.
 *
 * So this emits, from the same source the validator reads:
 *
 *   docs/taxonomy/README.md      Index: totals, distributions, per-domain links
 *   docs/taxonomy/<DOMAIN>.md    One file per domain, as GitHub-rendered tables
 *   docs/taxonomy/taxonomy.csv   One row per element, for spreadsheet analysis
 *
 * These ARE committed, unlike the built viewer. A 270 KB HTML blob churning on
 * every edit is noise; a Markdown table changing by three lines is the audit
 * record — seeing exactly what moved between two versions is the point.
 *
 * Usage:
 *   node tools/build-docs.ts            regenerate
 *   node tools/build-docs.ts --check    fail if stale (CI uses this)
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), '../..');
const DOMAINS_DIR = join(REPO_ROOT, 'content', 'competence', 'taxonomy', 'domains');
const OUT_DIR = join(REPO_ROOT, 'docs', 'taxonomy');

const check = process.argv.includes('--check');

interface Element { id: string; title: string; kind: string; levelCeiling: number; status: string }
interface Area { id: string; title: string; summary?: string; elements: Element[] }
interface Domain { id: string; title: string; kind: string; summary?: string; competencyAreas: Area[] }

const domains: Domain[] = readdirSync(DOMAINS_DIR)
  .filter((f) => f.endsWith('.yaml'))
  .sort()
  .flatMap((f) => {
    const doc = parseYaml(readFileSync(join(DOMAINS_DIR, f), 'utf8')) as { domains?: Domain[] };
    return doc.domains ?? [];
  });

const KIND_LABEL: Record<string, string> = {
  knowledge: 'Knowledge',
  skill: 'Skill',
  judgment: 'Judgment',
};

const LEVEL_LABEL: Record<number, string> = {
  1: 'Novice',
  2: 'Advanced Beginner',
  3: 'Competent',
  4: 'Proficient',
  5: 'Expert',
};

const elementsOf = (d: Domain) => d.competencyAreas.flatMap((a) => a.elements);
const allElements = domains.flatMap(elementsOf);

/** Escape pipes so a title containing one cannot break a Markdown table. */
const cell = (s: string) => s.replace(/\|/g, '\\|');

/* ------------------------------------------------------------------ */
/* Per-domain documents                                               */
/* ------------------------------------------------------------------ */

function domainDoc(d: Domain): string {
  const els = elementsOf(d);
  const kinds = { knowledge: 0, skill: 0, judgment: 0 } as Record<string, number>;
  const ceilings = { 3: 0, 4: 0, 5: 0 } as Record<number, number>;
  for (const e of els) {
    kinds[e.kind] = (kinds[e.kind] ?? 0) + 1;
    ceilings[e.levelCeiling] = (ceilings[e.levelCeiling] ?? 0) + 1;
  }

  const out: string[] = [];

  out.push(`# ${d.id} — ${d.title}`);
  out.push('');
  out.push(`[← All domains](README.md)`);
  out.push('');
  if (d.summary) {
    out.push(`> ${d.summary.trim().replace(/\s+/g, ' ')}`);
    out.push('');
  }
  out.push(
    `**${d.kind === 'core' ? 'Cross-cutting core' : 'Discipline pack'}** · ` +
      `${d.competencyAreas.length} competency areas · ${els.length} elements`,
  );
  out.push('');
  out.push(
    `Kind: ${kinds.knowledge} knowledge, ${kinds.skill} skill, ${kinds.judgment} judgment · ` +
      `Ceiling: ${ceilings[3]} L3, ${ceilings[4]} L4, ${ceilings[5]} L5`,
  );
  out.push('');
  out.push('---');
  out.push('');

  for (const a of d.competencyAreas) {
    out.push(`## ${a.id} — ${a.title}`);
    out.push('');
    if (a.summary) {
      out.push(`> ${a.summary.trim().replace(/\s+/g, ' ')}`);
      out.push('');
    }
    out.push('| ID | Element | Kind | Ceiling |');
    out.push('|---|---|---|---|');
    for (const e of a.elements) {
      out.push(
        `| \`${e.id}\` | ${cell(e.title)} | ${KIND_LABEL[e.kind] ?? e.kind} | ${e.levelCeiling} — ${LEVEL_LABEL[e.levelCeiling]} |`,
      );
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    '*Generated from `content/competence/taxonomy/domains/` by `npm run build:docs`. Do not edit this file — edit the YAML.*',
  );
  out.push('');

  return out.join('\n');
}

/* ------------------------------------------------------------------ */
/* Index                                                              */
/* ------------------------------------------------------------------ */

function indexDoc(): string {
  const out: string[] = [];

  const areaCount = domains.reduce((n, d) => n + d.competencyAreas.length, 0);
  const units = allElements.reduce((n, e) => n + e.levelCeiling, 0);

  const kinds = { knowledge: 0, skill: 0, judgment: 0 } as Record<string, number>;
  const ceilings = { 3: 0, 4: 0, 5: 0 } as Record<number, number>;
  for (const e of allElements) {
    kinds[e.kind] = (kinds[e.kind] ?? 0) + 1;
    ceilings[e.levelCeiling] = (ceilings[e.levelCeiling] ?? 0) + 1;
  }

  const pct = (n: number) => ((n / allElements.length) * 100).toFixed(1);

  out.push('# Taxonomy');
  out.push('');
  out.push(
    'The complete Metrology Competence System taxonomy, as reviewable documents. ' +
      'Every domain, competency area and element, with the attainable level ceiling and the kind of competence each represents.',
  );
  out.push('');
  out.push('**Three ways to read it, for three different jobs:**');
  out.push('');
  out.push('| | Best for |');
  out.push('|---|---|');
  out.push(
    '| These Markdown files | Reading linearly, reviewing a pull request, diffing two versions, printing |',
  );
  out.push(
    '| [`taxonomy.csv`](taxonomy.csv) | Spreadsheet analysis, filtering, pivot tables, importing elsewhere |',
  );
  out.push(
    '| [Interactive viewer](https://recamerino.github.io/metrology-competence-system/) | Searching and filtering across all domains at once |',
  );
  out.push('');
  out.push(
    'The authoritative source is [`content/competence/taxonomy/domains/`](../../content/competence/taxonomy/domains/). ' +
      'Everything here is generated from it and regenerated in CI, so it cannot drift.',
  );
  out.push('');
  out.push('---');
  out.push('');
  out.push('## Totals');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| Domains | ${domains.length} |`);
  out.push(`| Competency areas | ${areaCount} |`);
  out.push(`| Elements | ${allElements.length} |`);
  out.push(`| Assessable units | ${units} |`);
  out.push('');
  out.push(
    'An assessable unit is one element at one level. Every level is assessed at element scope, ' +
      'so a credential names exactly what was tested.',
  );
  out.push('');

  out.push('## Level ceiling');
  out.push('');
  out.push('The highest level attainable for an element. Not every element supports all five.');
  out.push('');
  out.push('| Ceiling | Meaning | Elements | Share |');
  out.push('|---|---|---|---|');
  for (const c of [3, 4, 5]) {
    out.push(`| ${c} | ${LEVEL_LABEL[c]} | ${ceilings[c]} | ${pct(ceilings[c]!)}% |`);
  }
  out.push('');
  out.push(
    '**L5 is reserved** for elements where a person could plausibly spend a career and still be learning, ' +
      'and where a defensible capstone with cross-organizational review is actually writable.',
  );
  out.push('');

  out.push('## Competence kind');
  out.push('');
  out.push('What kind of competence an element is, and therefore what evidence proves it.');
  out.push('');
  out.push('| Kind | The claim | What proves it | Elements | Share |');
  out.push('|---|---|---|---|---|');
  out.push(
    `| Knowledge | I understand this | Explanation, relation, analysis | ${kinds.knowledge} | ${pct(kinds.knowledge!)}% |`,
  );
  out.push(
    `| Skill | I can perform this | A witnessed work product | ${kinds.skill} | ${pct(kinds.skill!)}% |`,
  );
  out.push(
    `| Judgment | I can decide and defend it | A defence; often no single right answer | ${kinds.judgment} | ${pct(kinds.judgment!)}% |`,
  );
  out.push('');
  out.push(
    '**Authority is deliberately not a kind.** Knowledge, skill and judgment are earned and belong to a person. ' +
      'Authority is granted, and is a relationship between a person, an organization and a scope of work. ' +
      'Competency credentials are portable; authorizations are not. See [`../00-context.md`](../00-context.md).',
  );
  out.push('');

  for (const kind of ['core', 'discipline'] as const) {
    const group = domains.filter((d) => d.kind === kind);
    if (group.length === 0) continue;

    out.push(
      kind === 'core'
        ? '## Cross-cutting core domains'
        : '## Discipline packs',
    );
    out.push('');
    out.push(
      kind === 'core'
        ? 'Competencies every metrological role shares to some degree, including the adjacent ones that are routinely missed.'
        : 'Measurement-discipline depth. Separately versioned; a role profile selects from these rather than assuming them entire.',
    );
    out.push('');
    out.push('| Domain | Areas | Elements | K / S / J | L3 / L4 / L5 |');
    out.push('|---|---|---|---|---|');
    for (const d of group) {
      const els = elementsOf(d);
      const k = els.filter((e) => e.kind === 'knowledge').length;
      const s = els.filter((e) => e.kind === 'skill').length;
      const j = els.filter((e) => e.kind === 'judgment').length;
      const c3 = els.filter((e) => e.levelCeiling === 3).length;
      const c4 = els.filter((e) => e.levelCeiling === 4).length;
      const c5 = els.filter((e) => e.levelCeiling === 5).length;
      out.push(
        `| [**${d.id}** ${cell(d.title)}](${d.id}.md) | ${d.competencyAreas.length} | ${els.length} | ${k} / ${s} / ${j} | ${c3} / ${c4} / ${c5} |`,
      );
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push('## Reading an element ID');
  out.push('');
  out.push('`CM-03-014` — domain `CM-03`, element 014.');
  out.push('');
  out.push(
    '**The prefix records where the element was first created and is historical.** ' +
      'The authoritative domain and competency area are fields on the element, so an element can be ' +
      'reorganised without renaming an ID. IDs are append-only and never change: a credential attesting ' +
      '`CM-03-014` must resolve to the same element permanently, or the person holding it loses their evidence.',
  );
  out.push('');
  out.push(
    '*Generated by `npm run build:docs`. Do not edit these files — edit the YAML in `content/competence/taxonomy/domains/`.*',
  );
  out.push('');

  return out.join('\n');
}

/* ------------------------------------------------------------------ */
/* CSV                                                                */
/* ------------------------------------------------------------------ */

function csvDoc(): string {
  const q = (s: string | number) => {
    const v = String(s);
    return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
  };

  const rows = [
    [
      'domain_id',
      'domain_title',
      'domain_type',
      'area_id',
      'area_title',
      'element_id',
      'element_title',
      'kind',
      'level_ceiling',
      'status',
    ].join(','),
  ];

  for (const d of domains) {
    for (const a of d.competencyAreas) {
      for (const e of a.elements) {
        rows.push(
          [d.id, d.title, d.kind, a.id, a.title, e.id, e.title, e.kind, e.levelCeiling, e.status]
            .map(q)
            .join(','),
        );
      }
    }
  }

  return rows.join('\n') + '\n';
}

/* ------------------------------------------------------------------ */

const files = new Map<string, string>();
files.set('README.md', indexDoc());
files.set('taxonomy.csv', csvDoc());
for (const d of domains) files.set(`${d.id}.md`, domainDoc(d));

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const stale: string[] = [];
for (const [name, content] of files) {
  const path = join(OUT_DIR, name);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;

  if (check) {
    stale.push(name);
  } else {
    writeFileSync(path, content, 'utf8');
  }
}

if (check) {
  if (stale.length > 0) {
    console.error('Generated taxonomy documents are out of date:');
    for (const name of stale) console.error(`  docs/taxonomy/${name}`);
    console.error('');
    console.error('Run `npm run build:docs` and commit the result.');
    process.exit(1);
  }
  console.log(`Taxonomy documents are current (${files.size} files).`);
} else {
  console.log(`Wrote ${files.size} files to docs/taxonomy/`);
  console.log(`  ${domains.length} domains, ${allElements.length} elements`);
}
